"""
    Post processes the files generated by ifs.

     command input: product text file
     the generated image is written to a fixed location.
        (res.png)

"""
import sys
from PIL import Image

with open(sys.argv[1], 'r') as f:
    size = int(f.readline())
    data = []
    for str_row in f:
        row = map(int, filter(lambda r: len(r) > 1, str_row[:-1].split(',')))
        data.append(list(row))

abs_max = max(map(max, data))
print('Absolute maxiumum is %d' % abs_max)


img = Image.new('RGB', (size,size), "black")
pixels = img.load()
for y, row_data in enumerate(data):
    for x, rr in enumerate(row_data): 
        vv = int((255. * rr)/ abs_max)
        pixels[x,y] = (vv,vv,vv)

img.save('res.png')
